### ISSUE TITLE
你是mcbbs上的草五叶吗

### ISSUE THREAD

**Issue by xiaopangju** [AnKangPig/ankangpig#1]
如题

**Comment by AnKangPig** [comment]
我是。

**Comment by AnKangPig** [comment]
------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"xiaopangju"<notifications@github.com&gt;;
发送时间:&nbsp;2019年10月27日(星期天) 上午8:30
收件人:&nbsp;"AnKangPig/ankangpig"<ankangpig@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;[AnKangPig/ankangpig] 你是mcbbs上的草五叶吗 (#1)




我是。我就是草五叶。

**Comment by AnKangPig** [comment]
这真是尬聊......前两个不看了，我就是草五叶

**Comment by xiaopangju** [comment]
看上去你不太会用github，解决问题之后应该关闭这个issues（Comment左边的Close issue）

**Comment by sheep-realms** [comment]
吃瓜

**Comment by GCVillager** [comment]
吃瓜
