### ISSUE TITLE
说说看这个仓库为啥存在

### ISSUE THREAD

**Issue by xiaopangju** [AnKangPig/ankangpig#2]
我觉得用来当留言板可以，但是可以公开邮箱的，所以没太大意义
所以这个issue是来问问草五叶有没有在那个准备搬运mod的仓库里发issue，以及issue写的咋么样了

**Comment by sheep-realms** [comment]
吃瓜

**Comment by AnKangPig** [comment]
我已经风了。Aikini已经抢先求授权了，大加知道吧？
