### ISSUE TITLE
Java 13: What You Need to Know

### ISSUE THREAD

**Issue by NGT10086** [AnKangPig/ankangpig#6]
The latest issue of Java Magazine is now available for reading. Due to popular demand, all articles can be downloaded as individual PDF files. As you can tell from the list of articles below, we focus in this issue on the advances in Java 13, as well as delivering our usual set of articles on related topics, our book review, quizzes, editorial, and updated calendar.

**Comment by xiaopangju** [comment]
你在干啥

**Comment by NGT10086** [comment]
2333
